### ISSUE TITLE
Should not throw a `Errno::ENAMETOOLONG` for too long names.

### ISSUE THREAD

**Issue by berkes** [metricfu/metric_fu#246]
It generates its own names and can generate too long names. 

E.g. a file called `/home/user/projects/some_rediculously_long_projectname/db/migrate/20140819122639_move_quantity_from_library_to_conversion_factor_and_expressions_indicator_builder.rb` is, indeed a stupid name. But it just so happens our project has this name. This results in an error:

    /home/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/metric_fu-4.11.1/lib/metric_fu/io.rb:117:in `initialize': File name too long @ rb_sysopen - /home/user/Documenten/some_project/tmp/metric_fu/output/_home_user_some_project_name_that_is_too_long_db_migrate_20140819122639_move_quantity_from_library_to_conversion_factor_and_expressions_indicator_builder.rb.html (Errno::ENAMETOOLONG)

(note, filenames are edited due to privacy and disclosure-issues)

**Comment by MGotink** [comment]
I'm able to reproduce it, it's hotspots which doesn't like the filename:
```
/Users/martin/Documents/rails/metric_fu/lib/metric_fu/io.rb:117:in `initialize': File name too long @ rb_sysopen - /Users/martin/Documents/rails/metric_fu/tmp/metric_fu/output/lib_very_long_filename_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.rb.html (Errno::ENAMETOOLONG)
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/io.rb:117:in `open'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/io.rb:117:in `file_for'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/io.rb:112:in `io_for'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/io.rb:74:in `write_output'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/formatter/html.rb:30:in `write_template'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/templates/metrics_template.rb:67:in `block in write_file_data'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/templates/metrics_template.rb:62:in `each_pair'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/templates/metrics_template.rb:62:in `write_file_data'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/templates/metrics_template.rb:23:in `write'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/formatter/html.rb:57:in `save_templatized_result'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/formatter/html.rb:25:in `finish'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/reporter.rb:33:in `block in notify'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/reporter.rb:32:in `each'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/reporter.rb:32:in `notify'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/reporter.rb:12:in `finish'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/run.rb:22:in `measure'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/run.rb:8:in `run'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/cli/helper.rb:18:in `run'
	from /Users/martin/Documents/rails/metric_fu/lib/metric_fu/cli/client.rb:18:in `run'
	from /Users/martin/Documents/rails/metric_fu/bin/metric_fu:9:in `<top (required)>'
	from /Users/martin/.rvm/gems/ruby-2.1.5/bin/metric_fu:23:in `load'
	from /Users/martin/.rvm/gems/ruby-2.1.5/bin/metric_fu:23:in `<main>'
	from /Users/martin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/martin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```
I think we can fix the issue by hashing the hotspots output filenames. I'll have a look.
