### ISSUE TITLE
flog-4.4.0/lib/flog.rb:175:in `binread': Is a directory @ io_fread - app (Errno::EISDIR)

### ISSUE THREAD

**Issue by americodls** [metricfu/metric_fu#273]
I was trying to run metric_fu against my project (Rails 4.2.6 with Ruby 2.3.0) and I got this:

```
~/github/rip(master ✗) metric_fu
******* STARTING METRIC stats
******* ENDING METRIC stats
******* STARTING METRIC churn
******* ENDING METRIC churn
******* STARTING METRIC flay
******* ENDING METRIC flay
******* STARTING METRIC flog
/Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/flog-4.4.0/lib/flog.rb:175:in `binread': Is a directory @ io_fread - app (Errno::EISDIR)
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/flog-4.4.0/lib/flog.rb:175:in `block in flog'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/flog-4.4.0/lib/flog.rb:172:in `each'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/flog-4.4.0/lib/flog.rb:172:in `flog'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/flog-4.4.0/lib/flog_cli.rb:164:in `flog'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/metrics/flog/generator.rb:16:in `emit'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/generator.rb:104:in `generate_result'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/reporting/result.rb:48:in `add'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/run.rb:21:in `block in measure'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/run.rb:19:in `each'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/run.rb:19:in `measure'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/run.rb:9:in `run'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/cli/helper.rb:19:in `run'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/lib/metric_fu/cli/client.rb:19:in `run'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/gems/metric_fu-4.12.0/bin/metric_fu:9:in `<top (required)>'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/bin/metric_fu:23:in `load'
	from /Users/americodls/.rvm/gems/ruby-2.3.0@rip/bin/metric_fu:23:in `<main>'
```

**Comment by americodls** [comment]
```ruby
{"Ruby"=>
  {"Engine"=>"ruby",
   "Version"=>"2.3.0",
   "Patchlevel"=>0,
   "Ripper Support"=>true,
   "Rubygems Version"=>"2.5.1",
   "Long Description"=>
    "ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]"},
 "Environment"=>
  {"VERBOSE"=>"false",
   "External Encoding"=>"UTF-8",
   "Internal Encoding"=>"",
   "Host Architecture"=>"x86_64-apple-darwin15.3.0",
   "Ruby Prefix"=>"/Users/americodls/.rvm/rubies/ruby-2.3.0",
   "Ruby Options"=>""},
 "MetricFu"=>
  {"Version"=>"4.12.0",
   "Verbose Mode"=>false,
   "Enabled Metrics"=>
    [:stats,
     :churn,
     :flay,
     :flog,
     :cane,
     :rails_best_practices,
     :reek,
     :roodi,
     :saikuro,
     :hotspots],
   "Dependencies"=>
    [{"name"=>"flay", "version"=>"2.8.0"},
     {"name"=>"churn", "version"=>"0.0.35"},
     {"name"=>"flog", "version"=>"4.4.0"},
     {"name"=>"reek", "version"=>"2.2.1"},
     {"name"=>"cane", "version"=>"2.6.2"},
     {"name"=>"rails_best_practices", "version"=>"1.16.0"},
     {"name"=>"saikuro", "version"=>[">= 1.1.3", "~> 1.1"]},
     {"name"=>"roodi", "version"=>"3.3.1"},
     {"name"=>"code_metrics", "version"=>"0.1.3"},
     {"name"=>"redcard", "version"=>"1.1.0"},
     {"name"=>"coderay", "version"=>"1.1.1"},
     {"name"=>"multi_json", "version"=>"1.12.1"},
     {"name"=>"launchy", "version"=>"2.4.3"},
     {"name"=>"rcov", "version"=>["~> 0.8"]}]}}
```

**Comment by americodls** [comment]
I guess the gem flog breaks compatibility here: https://github.com/seattlerb/flog/commit/858d125e27ba60564b0903fadb5e0988c9a5c19a

**Comment by felipegs** [comment]
+1

**Comment by manusajith** [comment]
any known workarounds or fixes ?

**Comment by felipegs** [comment]
Fix older version of flog on Gemfile

**Comment by bf4** [comment]
I'm not paying a lot of attention to metric_fu right now and would love to help enable you to maintain it :)

**Comment by americodls** [comment]
Maybe I can help.
I am waiting some instructions.
Em 8 de jun de 2016 00:36, "Benjamin Fleischer" <notifications@github.com>
escreveu:

**Comment by manusajith** [comment]
same here can lend a hand in maintaining it. with little help from @bf4 :)

**Comment by aliakhtar** [comment]
Getting the same error. What's the workaround?

**Comment by jkeam** [comment]
Thanks @bergholdt, I applied your work around and things are working well.

At the risk of being overly explicit, to apply the fix, in your Gemfile, just reference the gem like this:

```ruby
gem 'metric_fu', git: 'https://github.com/bergholdt/metric_fu.git'
```

**Comment by jkeam** [comment]
Of course you could also fork, apply the fix to your own fork and reference that one.

**Comment by bf4** [comment]
I'd be happy to give commit to anyone at this point who can help.  I've been neglecting metric_fu far too much.

**Comment by jkeam** [comment]
I'd love to help.  I think the first thing to do is get the build working again.  Then look at the PRs that are out there that solve this.  Looks like americodis's solves it https://github.com/metricfu/metric_fu/pull/274 but adds a hard dep on `path_expander`
where as bergholdt's looks good, but could probably use a test or two around it.  https://github.com/metricfu/metric_fu/pull/278.

I'll be opening a PR soon.

**Comment by jkeam** [comment]
https://github.com/metricfu/metric_fu/pull/279

**Comment by bergholdt** [comment]
@jkeam I updated to generator_spec to verify that fog receives a list of files matching lib directory.
